### ISSUE TITLE
Weird behavior after changing routes

### ISSUE THREAD

**Issue by NevenLiang** [shipshapecode/angular-shepherd#271]
### Reproduction

1. Click `Start Tour` button. Now the tour flow works well and all buttons work as expected.
2. Click the `About` router link above at navigation and then back to home page.
3. Click `Start Tour` button again. Except close button at the top right conner, 
there will be something wrong with other buttons in **step 1**. If try to click them one by one, you will get the result as screenshot shown below.

![image](https://user-images.githubusercontent.com/52629607/83137353-9db07e80-a11b-11ea-98be-680e4b62b6bc.png)

### Demo
https://codesandbox.io/s/guide-tour-65yrm

---

### Edited:

I am using it in Angular v8.

It seems that there are multiple tour instance. If there is anything I can do to destroy the old tour instance when leaving the page(component)? How to fix it?

Thank you!

**Comment by rwwagner90** [comment]
@NevenLiang yes, probably need to destroy when you change pages.

**Comment by NevenLiang** [comment]
@rwwagner90 Do you have any clues about why it happen and any advices to handle it with or without Angular? I can't find a related method in [the docs of tour](https://shepherdjs.dev/docs/Tour.html). 

I have tried to add the code as following, but it doesn't work.

```js
export class HomeComponent implements OnDestroy {
  constructor(private guideTour : ShepherdService) {}

  ngOnDestroy() {
	this.guideTour = null;
  }

  startTour() {
    // set up and start guide tour
  }
}
```

**Comment by rwwagner90** [comment]
@NevenLiang I just took a look at the codesandbox, and I am unsure of what the problem is. I am not an Angular dev, so I am not sure if we have something setup wrong or what, but `addSteps` should be setting `tourObject` to a new tour, so there should be no way multiple get triggered.

It almost seems like Angular registers the service multiple times and somehow call the method to create new tours multiple times.

**Comment by NevenLiang** [comment]
I have noticed that the tour flow is fine, but the problem is step-1 keeps showing on the screen and only clicking on the cancel(X) icon can make step-1 disappeared. 

If we click the **Next** button in step-1, step-1 should disappear. If we click on the **Exit** button or the **Next** button on step-2, the mask does disappear, which means `cancel()` or `complete()` have been called, but step-1 is still on the screen.

**Comment by rwwagner90** [comment]
@NevenLiang sorry, perhaps I was not clear in my previous message. I agree with you there is a bug, but I am not an Angular dev, so I do not know what we may have done wrong in this library.

`addSteps` should be setting `tourObject` to a new tour, so there should be no way multiple get triggered.

It almost seems like Angular registers the service multiple times and somehow calls the method to create new tours multiple times.

**Comment by NevenLiang** [comment]
@rwwagner90 OK. 

I am still trying to fix it. I have found some new clues.

![image](https://user-images.githubusercontent.com/52629607/83190078-77630100-a164-11ea-9696-c690b94a3a99.png)

There are two `step-1` popups, which are `popup-1` and `popup-3` (You can change the `left` and `bottom` property of `popup-1` to make it clear). The `popup-1` is like a controller, it can only be closed by clicking cancel icon. The `popup-2` and `popup-3` is the normal step.

**Comment by rwwagner90** [comment]
@NevenLiang Is there new information there? We know Angular is creating multiple instances here. I am not an Angular dev, so it would be helpful if someone who knew how Angular services work could chime in here. It appears the service instantiates itself every time you enter the route, instead of once for the application. We need it to only instantiate one time, and I need guidance from someone who is good with Angular to help us remedy this in the library.

**Comment by rwwagner90** [comment]
@NevenLiang I believe I got it to work: https://codesandbox.io/s/guide-tour-8znbk

I think the issue is you need to setup the service in your `app.component` so there is a single service created. I believe doing it in child components causes there to be a new service instantiated every time the component is rendered.

We probably need to make the docs more clear about this.

**Comment by NevenLiang** [comment]
@rwwagner90 Sorry for the late response. 

Yes, I set it as component's provider because I use shepherd only in that component now, which leads to instantiate every time the component is rendered.

Thank you so much!

**Comment by rwwagner90** [comment]
@NevenLiang you're welcome! Perhaps we should mention this in the README?
